# Window rules
# ............
windowrule = float 1,match:class pavucontrol
windowrule = float 1,match:class blueman-manager
windowrule = float 1,match:class kitty
windowrule = match:fullscreen true,match:class smplayer
windowrule = match:fullscreen true,match:class mpv
windowrule = match:fullscreen true,match:class floorp
#windowrulev2 = opacity 0.85 0.95,class:^thunar
#windowrulev2 = opacity 0.95 0.85,class:^mousepad
